### ISSUE TITLE
Tag for v1.1.0

### ISSUE THREAD

**Issue by tcitbiint3** [yuchdev/code_generator#11]
For further development it would be good to create a v.1.1.0 tag. Proposal:  v1.1.0 for https://github.com/yuchdev/code_generator/commit/2976c36a0497b02645b4e49d8e838fa65069a96b on the master branch?

**Comment by yuchdev** [comment]
I have bigger plans.
I would like to convert the application into a [PIP package](https://github.com/yuchdev/code_generator/issues/12)
It includes a full CI pipeline (including tagging, wheel upload, etc)
I used such a configuration on a couple of PIP packages.
If you use the generator for your needs, I can find time for cooperation, and we make it a PIP packet.

**Comment by tcitbiint3** [comment]
I never created a pip package on my own so that it would be interesting for me to see how it works from scratch. Unfortunately I am limited in time.

**Comment by yuchdev** [comment]
Cool, I'm planning to create it today
However, code_generator name is occupied by some dead project
I rename our project to PyCodegen
