### ISSUE TITLE
PIP Package

### ISSUE THREAD

**Issue by yuchdev** [yuchdev/code_generator#12]

**Comment by yuchdev** [comment]
Use the configuration from [ExtractVersion](https://github.com/yuchdev/ExtractVersion) package

**Comment by yuchdev** [comment]
@tcitbiint3 you can take a look at the branch [code-12-pip](https://github.com/yuchdev/code_generator/tree/code-12-pip) (already merged). It contains the whole toolchain implementation for creating a PIP package.
The only thing left is to publish the package on PyPi.org, so that we could `pip install` it from Actions pipeline

**Comment by yuchdev** [comment]
And the last update - `PyCodegen` contradicts the naming convention, I made the package name `code-generation`, and left the repo `code-generator`.
Thank you for your interest in the project.

**Comment by tcitbiint3** [comment]
Very nice, thanks!
