### ISSUE TITLE
Actions pipeline fails with official pip install in case of incompatible changes

### ISSUE THREAD

**Issue by tcitbiint3** [yuchdev/code_generator#18]
@yuchdev 

Using the pip version of the project will lead to a failing Actions pipeline in case of incompatible changes: https://github.com/yuchdev/code_generator/blob/304b7b682be5614018bcaeaf6c25873c77cbcd5b/.github/workflows/python-app.yml#L36
Potential bugfix available with PR https://github.com/yuchdev/code_generator/pull/17

Is this the intended behavior?

**Comment by yuchdev** [comment]
@tcitbiint3 I don't quite understand, what does it mean "incompatible changes"?
Would you extend the example, please?

**Comment by yuchdev** [comment]
By the way, could you change the string to `python -m pip install code-generation`?
For uniform `pip` use

**Comment by tcitbiint3** [comment]
> @tcitbiint3 I don't quite understand, what does it mean "incompatible changes"? Would you extend the example, please?

Yes, changes which influence the output of the example or changes which change a function header in a incompatible way, e.g. when defining a parameter mandatory which was optional before, so that the execution of the examples is not possible with the version behind pip install.  Using the current version of the repository will test the current version, which makes more sense or am I wrong?

In case of PR #17, in which the example was extended, and the current "python -m pip install code-generation", a new version has to be pushed to pip in order to get Actions pipeline without errors.

**Comment by yuchdev** [comment]
"which change a function header in a incompatible way, e.g. when defining a parameter mandatory which was optional before" yeah, I met such inconveniences before.
For that exact case, package user can define the exact version of the package in the `requirements.txt`
`code-generation==2.1.1`
I think, we can let this minor issue exist, until such incompatibility explicitly happen
And we can merge the PR

**Comment by yuchdev** [comment]
BTW, we have an assertion after the merge
`AssertionError: Lists differ: [] != ['class.cpp']`

**Comment by tcitbiint3** [comment]
> 

Yes, this is because of the test execution with v2.1.1 instead of the version of the PR. in the PR, the tests are changed in order to test the changes properly. Therefore `pip install code-generation` was removed in the PR.

**Comment by yuchdev** [comment]
Okay, let's try out

**Comment by yuchdev** [comment]
I fixed it with my package release script.
It handles the installation, reinstallation and dev mode of PIP packages.
It's funny I made it and forgot about it:)
Now it works just fine

**Comment by tcitbiint3** [comment]
This looks like the best solution! Thanks!

**Comment by yuchdev** [comment]
@tcitbiint3
Sorry to bother you, if you're busy, you can safely ignore my request.
But could you provide a couple of real-world examples of C++ code generation?
Unless it is under some proprietary license.
My use of the library is under a commercial license, unfortunately.

I want to move the library to another level and include support for other languages.
For that, I need documentation and examples for each of them.
Again, if you find it easy. You already contributed a lot to the project.
